# main.py (SEQUENCED SIMULATION FLOW WITH TASK + CACHE DECISION + GRU-PPO)
import numpy as np
from communication_model import compute_rate
from sagin_env import SAGINEnv
from ppo_gru_agent import GRUPPOAgent
from visualize_network import create_visualizations

# Grid dimensions
X, Y = 3, 3

# Content parameters
num_contents = 10

# Resource constraints
cache_size = 10  # MB
compute_power_uav = 100  # Compute units per second
compute_power_sat = 500  # Compute units per second
compute_power_gv = 50  # Compute units per second for ground vehicles
energy = 10000  # Energy units
max_queue = 10  # Max tasks per queue

# Network parameters
num_sats = 2
num_vehicles = 15  # Number of ground vehicles in the simulation
num_iot_per_region = 15
max_active_iot = 8
ofdm_slots = 9

# Simulation parameters
duration = 1.0  # Seconds per time step

# RL parameters
obs_dim = 28  # example dim for observation vector, must match UAV.observe output

# Initialize environment and PPO agent
env = SAGINEnv(X, Y, duration, cache_size, compute_power_uav, compute_power_sat, compute_power_gv, energy, max_queue, num_sats, num_iot_per_region, max_active_iot, ofdm_slots, num_vehicles=num_vehicles)
ppo_agent = GRUPPOAgent(obs_dim=obs_dim, num_contents=num_contents)

# Run simulation
for timestep in range(500):
    print(f"\n=== Time Slot {timestep + 1} ===")

    # (1) IoT activation, vehicle movement, and data aggregation
    env.collect_iot_data()

    # (2) Allocate OFDM slots
    env.allocate_ofdm_slots()

    # (2.5) Update satellite coverage
    for sat in env.sats:
        sat.update_coverage(timestep)

    # (3) Only UAVs with slots upload content to satellites
    env.upload_to_satellites()

    # (4) Sync content across satellites
    env.sync_satellites()

    # (5) Generate tasks and make offloading decisions
    env.generate_and_offload_tasks()

    # (6) UAV-local caching based on PPO agent decisions
    actions = {}
    for (x, y), uav in env.uavs.items():
        uav.current_time = timestep
        obs = uav.observe(
            neighbor_loads=np.zeros((4, 1)),  # Simplified for test run
            satellite_in_range=[1] * len(env.sats),
            activation_mask=np.ones(num_contents)
        )
        cache_action, offload_action, _ = ppo_agent.act(obs)
        actions[(x, y)] = {'cache': cache_action, 'offload': offload_action}

    env.step(actions, timestep)

    # Print key stats every 50 timesteps
    if (timestep + 1) % 50 == 0:
        # Count active vehicles
        active_vehicles = len(env.vehicles)
        
        # Count total tasks by tier
        total_vehicle_tasks = sum(stats['generated'] for stats in env.task_stats['ground_vehicle'].values())
        total_uav_tasks = sum(stats['generated'] for stats in env.task_stats['uav'].values())
        total_satellite_tasks = sum(stats['received'] for stats in env.task_stats['satellite'].values())
        
        print(f"\n--- Stats at timestep {timestep + 1} ---")
        print(f"Active ground vehicles: {active_vehicles}")
        print(f"Total tasks generated - Vehicles: {total_vehicle_tasks}, UAVs: {total_uav_tasks}, Satellites: {total_satellite_tasks}")
        print(f"Total dropped tasks: {env.dropped_tasks}")
        
        # Generate visualizations at specific intervals
        if (timestep + 1) % 100 == 0:
            try:
                create_visualizations(env, timestep)
                print(f"Created visualizations for timestep {timestep + 1}")
            except Exception as e:
                print(f"Error generating visualizations: {e}")

# Log summary
print("\n=== Last 10 Task Logs ===")
for entry in env.task_log[-10:]:
    print("Task Log Entry:", entry)

# Log success summary
print("\n=== Task Success Summary ===")
for entry in env.success_log:
    print(f"UAV {entry['coord']} completed {entry['completed']} tasks, "
          f"of which {entry['successful']} met delay bound.")

# === Task Success Summary ===
total_completed = sum(e['completed'] for e in env.success_log)
total_successful = sum(e['successful'] for e in env.success_log)
success_rate = 100 * total_successful / total_completed if total_completed else 0
print(f"Overall Task Success Rate: {success_rate:.2f}%")

# === Per-Tier Performance ===
print("\n=== Per-Tier Performance ===")

# Ground Vehicle performance
print("\n== Ground Vehicle Performance ==")
total_vehicle_generated = sum(stats['generated'] for stats in env.task_stats['ground_vehicle'].values())
total_vehicle_completed = sum(stats['completed'] for stats in env.task_stats['ground_vehicle'].values())
total_vehicle_successful = sum(stats['successful'] for stats in env.task_stats['ground_vehicle'].values())

if total_vehicle_generated > 0:
    print(f"Total tasks generated by vehicles: {total_vehicle_generated}")
    if total_vehicle_completed > 0:
        vehicle_completion_rate = 100 * total_vehicle_completed / total_vehicle_generated
        vehicle_success_rate = 100 * total_vehicle_successful / total_vehicle_completed
        print(f"Task completion rate: {vehicle_completion_rate:.2f}%")
        print(f"Task success rate (within deadline): {vehicle_success_rate:.2f}%")
    else:
        print("No tasks completed by vehicles")

    # Top 5 most active vehicles
    active_vehicles = sorted(env.task_stats['ground_vehicle'].items(), 
                            key=lambda x: x[1]['generated'], reverse=True)[:5]
    print("\nTop 5 most active vehicles:")
    for v_id, stats in active_vehicles:
        if stats['completed'] > 0:
            v_success_rate = 100 * stats['successful'] / stats['completed']
            print(f"Vehicle {v_id} — Generated: {stats['generated']}, "
                  f"Completed: {stats['completed']}, Success: {v_success_rate:.1f}%")

# UAV performance
print("\n== UAV Performance ==")
print("Per-UAV Task Performance:")
for (x, y), stats in env.task_stats['uav'].items():
    if stats['completed'] > 0:
        rate = 100 * stats['successful'] / stats['completed']
        print(f"UAV ({x},{y}) — Generated: {stats['generated']}, "
              f"Completed: {stats['completed']}, Within Deadline: {stats['successful']} ({rate:.1f}%)")

print("\nCache Hit Rates per UAV:")
for (x, y), uav in env.uavs.items():
    if uav.total_tasks > 0:
        hit_rate = 100 * uav.cache_hits / uav.total_tasks
        print(f"UAV ({x},{y}) — Cache Hit Rate: {hit_rate:.1f}%")

# Satellite performance
print("\n== Satellite Performance ==")
for sat_id, stats in env.task_stats['satellite'].items():
    if stats['received'] > 0:
        completion_rate = 100 * stats['completed'] / stats['received'] if stats['received'] > 0 else 0
        success_rate = 100 * stats['successful'] / stats['completed'] if stats['completed'] > 0 else 0
        print(f"Satellite {sat_id} — Received: {stats['received']}, "
              f"Completed: {stats['completed']} ({completion_rate:.1f}%), "
              f"Within Deadline: {stats['successful']} ({success_rate:.1f}%)")

# Overall statistics
print("\n=== Overall Statistics ===")
print(f"Total Dropped Tasks: {env.dropped_tasks}")

# Task offloading distribution
offload_counts = {}
for entry in env.task_log:
    target = entry['assigned_to']
    offload_category = target.split('_')[0]  # Extract category (local, neighbor, satellite, etc.)
    offload_counts[offload_category] = offload_counts.get(offload_category, 0) + 1

print("\nTask Offloading Distribution:")
total_tasks = sum(offload_counts.values())
for category, count in offload_counts.items():
    percentage = 100 * count / total_tasks
    print(f"{category}: {count} tasks ({percentage:.1f}%)")
